### ISSUE TITLE
All events being unintentionally filtered

### ISSUE THREAD

**Issue by ivanagas** [plibither8/posthog-filter-out-plugin#1]
I've been testing out this plugin to potentially add to a tutorial I'm writing, and no matter the schema I enter, it seems to be filtering all of the events.

It is processing events and not raising any issues. An empty schema is allowing events to be injested, but no matter the what schema I tried (from very basic to multi-step), the app seems to filter all events out. 

Some potential issues and fixes:
1. I could be misconfiguring the schema. For example, using `pathname` to filter an autocaptured event instead of `$pathname` if the app doesn't handle for that.
2. Instead of defaulting to filtering event if it doesn't pass the checks (or error), you could set it to return the event. 
3. Better logging or errors for when an event gets filtered.

Let me know if I'm missing something.

**Comment by plibither8** [comment]
Thanks a lot Ian! I'm travelling right now so I'm not too sure I'd be able to look into the issue myself.

I think @pjhul created a PR to fix this issue and trusting him on it! :D
