### ISSUE TITLE
Support logical operators

### ISSUE THREAD

**Issue by beggers** [plibither8/posthog-filter-out-plugin#4]
Hello!

My company, Chroma, is a Posthog user. One of our action items from a recent incident is to better filter our Posthog events. This filter seems to be the recommended way to do so.

We'd like a way to add logical operators in filters, for example to filter `if condition_1 OR condition_2 OR (condition_3 AND condition_4)`. I believe this is the only way for us to get the filtering behavior we want.

(Issue submitted in this repo since the forked repo doesn't seem to have an issues tab)

**Comment by plibither8** [comment]
Hi @beggers! Development and support for this plugin has been moved to [PostHog/posthog-filter-out-plugin](PostHog/posthog-filter-out-plugin). I'd recommend creating this issue there. Thanks!
